/**
 * Cloud Presets Configuration
 *
 * Each preset defines settings for all three cloud layers plus environment settings.
 * These can be quickly applied via the Leva dropdown to experiment with different looks.
 */

export const cloudPresets = {
  // Bright, happy day with fluffy white clouds
  'Fluffy Day': {
    environment: {
      backgroundColor: '#87CEEB',  // Sky blue
      ambientIntensity: 2.0,
      directionalIntensity: 0,
      directionalPosition: [10, 20, 10],
      fogEnabled: false,
      fogColor: '#87CEEB',
      fogNear: 10,
      fogFar: 100,
      cameraFov: 60,
    },
    layers: {
      front: {
        visible: true,
        seed: 1,
        segments: 25,
        volume: 8,
        opacity: 0.9,
        fade: 100,
        growth: 6,
        speed: 0.2,
        boundsX: 20,
        boundsY: 8,
        boundsZ: 15,
        color: '#ffffff',
        positionX: 0,
        positionY: 5,
        positionZ: 0,
      },
      mid: {
        visible: true,
        seed: 10,
        segments: 20,
        volume: 10,
        opacity: 0.8,
        fade: 150,
        growth: 8,
        speed: 0.15,
        boundsX: 30,
        boundsY: 10,
        boundsZ: 20,
        color: '#ffffff',
        positionX: 0,
        positionY: 10,
        positionZ: -10,
      },
      back: {
        visible: true,
        seed: 20,
        segments: 15,
        volume: 12,
        opacity: 0.6,
        fade: 200,
        growth: 10,
        speed: 0.1,
        boundsX: 40,
        boundsY: 12,
        boundsZ: 30,
        color: '#ffffff',
        positionX: 0,
        positionY: 15,
        positionZ: -25,
      },
    },
    animation: {
      autoRotate: false,
      rotationSpeed: 0.1,
      drift: true,
      driftSpeed: 0.5,
      colorCycle: false,
    },
  },

  // Dark, moody storm clouds
  'Stormy': {
    environment: {
      backgroundColor: '#1a1a2e',
      ambientIntensity: 0.3,
      directionalIntensity: 0.8,
      directionalPosition: [-5, 10, 5],
      fogEnabled: true,
      fogColor: '#2a2a3e',
      fogNear: 5,
      fogFar: 60,
      cameraFov: 70,
    },
    layers: {
      front: {
        visible: true,
        seed: 42,
        segments: 40,
        volume: 15,
        opacity: 0.95,
        fade: 80,
        growth: 4,
        speed: 0.4,
        boundsX: 25,
        boundsY: 10,
        boundsZ: 20,
        color: '#3a3a4a',
        positionX: 0,
        positionY: 3,
        positionZ: 5,
      },
      mid: {
        visible: true,
        seed: 55,
        segments: 35,
        volume: 20,
        opacity: 0.9,
        fade: 100,
        growth: 5,
        speed: 0.35,
        boundsX: 35,
        boundsY: 12,
        boundsZ: 25,
        color: '#4a4a5a',
        positionX: 0,
        positionY: 8,
        positionZ: -5,
      },
      back: {
        visible: true,
        seed: 77,
        segments: 30,
        volume: 25,
        opacity: 0.7,
        fade: 150,
        growth: 6,
        speed: 0.25,
        boundsX: 45,
        boundsY: 15,
        boundsZ: 35,
        color: '#5a5a6a',
        positionX: 0,
        positionY: 12,
        positionZ: -20,
      },
    },
    animation: {
      autoRotate: false,
      rotationSpeed: 0.05,
      drift: true,
      driftSpeed: 1.0,
      colorCycle: false,
    },
  },

  // Warm sunset with golden/pink tinted clouds
  'Sunset': {
    environment: {
      backgroundColor: '#1a0a1a',
      ambientIntensity: 0.5,
      directionalIntensity: 3.0,
      directionalPosition: [-20, 5, 10],
      fogEnabled: true,
      fogColor: '#ff6b4a',
      fogNear: 20,
      fogFar: 120,
      cameraFov: 55,
    },
    layers: {
      front: {
        visible: true,
        seed: 8,
        segments: 22,
        volume: 6,
        opacity: 0.85,
        fade: 120,
        growth: 5,
        speed: 0.1,
        boundsX: 20,
        boundsY: 6,
        boundsZ: 15,
        color: '#ff9966',
        positionX: -5,
        positionY: 3,
        positionZ: 0,
      },
      mid: {
        visible: true,
        seed: 15,
        segments: 25,
        volume: 8,
        opacity: 0.75,
        fade: 150,
        growth: 7,
        speed: 0.08,
        boundsX: 30,
        boundsY: 8,
        boundsZ: 20,
        color: '#ffcc99',
        positionX: 0,
        positionY: 8,
        positionZ: -10,
      },
      back: {
        visible: true,
        seed: 25,
        segments: 18,
        volume: 10,
        opacity: 0.5,
        fade: 200,
        growth: 10,
        speed: 0.05,
        boundsX: 40,
        boundsY: 10,
        boundsZ: 30,
        color: '#ff6699',
        positionX: 5,
        positionY: 12,
        positionZ: -25,
      },
    },
    animation: {
      autoRotate: false,
      rotationSpeed: 0.02,
      drift: true,
      driftSpeed: 0.2,
      colorCycle: true,
    },
  },

  // Sparse, delicate wispy clouds
  'Minimal/Wispy': {
    environment: {
      backgroundColor: '#e8f4f8',
      ambientIntensity: 1.5,
      directionalIntensity: 2.0,
      directionalPosition: [15, 25, 15],
      fogEnabled: false,
      fogColor: '#e8f4f8',
      fogNear: 30,
      fogFar: 150,
      cameraFov: 50,
    },
    layers: {
      front: {
        visible: true,
        seed: 3,
        segments: 8,
        volume: 3,
        opacity: 0.5,
        fade: 200,
        growth: 12,
        speed: 0.05,
        boundsX: 30,
        boundsY: 5,
        boundsZ: 25,
        color: '#ffffff',
        positionX: 5,
        positionY: 8,
        positionZ: 0,
      },
      mid: {
        visible: true,
        seed: 12,
        segments: 6,
        volume: 2,
        opacity: 0.4,
        fade: 250,
        growth: 15,
        speed: 0.03,
        boundsX: 40,
        boundsY: 6,
        boundsZ: 30,
        color: '#f8f8ff',
        positionX: -5,
        positionY: 12,
        positionZ: -15,
      },
      back: {
        visible: false,
        seed: 30,
        segments: 4,
        volume: 2,
        opacity: 0.3,
        fade: 300,
        growth: 18,
        speed: 0.02,
        boundsX: 50,
        boundsY: 8,
        boundsZ: 40,
        color: '#f0f0ff',
        positionX: 0,
        positionY: 18,
        positionZ: -30,
      },
    },
    animation: {
      autoRotate: false,
      rotationSpeed: 0.01,
      drift: true,
      driftSpeed: 0.1,
      colorCycle: false,
    },
  },

  // Heavy overcast with full cloud coverage
  'Dense Overcast': {
    environment: {
      backgroundColor: '#6a7a8a',
      ambientIntensity: 0.8,
      directionalIntensity: 1.2,
      directionalPosition: [0, 20, 0],
      fogEnabled: true,
      fogColor: '#8a9aaa',
      fogNear: 5,
      fogFar: 50,
      cameraFov: 65,
    },
    layers: {
      front: {
        visible: true,
        seed: 33,
        segments: 50,
        volume: 20,
        opacity: 0.6,
        fade: 60,
        growth: 3,
        speed: 0.15,
        boundsX: 35,
        boundsY: 8,
        boundsZ: 30,
        color: '#b8c8d8',
        positionX: 0,
        positionY: 2,
        positionZ: 5,
      },
      mid: {
        visible: true,
        seed: 44,
        segments: 45,
        volume: 25,
        opacity: 0.5,
        fade: 80,
        growth: 4,
        speed: 0.12,
        boundsX: 40,
        boundsY: 10,
        boundsZ: 35,
        color: '#c8d8e8',
        positionX: 0,
        positionY: 6,
        positionZ: -5,
      },
      back: {
        visible: true,
        seed: 55,
        segments: 40,
        volume: 30,
        opacity: 0.4,
        fade: 100,
        growth: 5,
        speed: 0.08,
        boundsX: 50,
        boundsY: 12,
        boundsZ: 40,
        color: '#d8e8f8',
        positionX: 0,
        positionY: 10,
        positionZ: -15,
      },
    },
    animation: {
      autoRotate: false,
      rotationSpeed: 0.05,
      drift: true,
      driftSpeed: 0.8,
      colorCycle: false,
    },
  },
};

// Get preset names for dropdown
export const presetNames = Object.keys(cloudPresets);

// Default preset to load on startup
export const defaultPreset = 'Fluffy Day';
